// packages/stencil-xstate-router/src/components/xstate-router/xstate-router.tsx
import { Component, Prop, State, ComponentInterface } from '@stencil/core';
import { StateMachine, interpret, Interpreter, EventObject } from 'xstate';
import { Options, Renderer } from 'stencil-xstate/dist/types';
import {
  ComponentProps,
  ComponentRenderer,
  RouteCondition,
  RouteMeta,
  RouteEvent,
  merge,
  renderComponent,
  RouteHandler,
  StateRenderer,
  NavigationHandler
} from './index';
import 'stencil-xstate';

@Component({
  tag: 'xstate-router',
  shadow: false
})
export class XStateRouter implements ComponentInterface {
  @State() private service: Interpreter<any, any, EventObject>;
  @State() private subscriptions: Set<VoidFunction> = new Set();

  /**
   * An XState machine
   */
  @Prop() machine!: StateMachine<any, any, EventObject>;

  /**
   * Interpreter options
   */
  @Prop() options?: Options = {
    immediate: false
  };

  /**
   * Renderer for states
   */
  @Prop() stateRenderer: StateRenderer<any, any, RouteEvent>;

  /**
   * Renderer for components
   */
  @Prop() componentRenderer: ComponentRenderer<
    any,
    any,
    EventObject
  > = renderComponent;

  /**
   * Callback for route subscriptions
   */
  @Prop() route!: RouteHandler<any, any, RouteEvent>;

  /**
   * Callback for url changes
   */
  @Prop() navigate!: NavigationHandler;

  componentWillLoad() {
    this.service = interpret(this.machine, this.options);

    const routes = this.machine.on['ROUTE'];
    if (!routes) {
      throw new Error('no ROUTE events found on root node');
    }

    routes.forEach(
      ({ cond: { path } }: { cond?: RouteCondition<any, RouteEvent> }) =>
        this.route([{ path }], this.service.send).forEach(unsubscribe =>
          this.subscriptions.add(unsubscribe)
        )
    );

    this.service.onEvent((event: RouteEvent) => {
      if (event.type === 'ROUTED') {
        this.navigate(event.url);
      }
    });
  }

  componentDidLoad() {
    this.service.start();
  }

  componentDidUnload() {
    this.subscriptions.forEach(unsubscribe => unsubscribe());

    this.service.stop();
  }

  render() {
    const componentRenderer: Renderer<any, any, EventObject> = (
      current,
      send,
      service
    ) => {
      const { component, ...params }: RouteMeta = merge(current.meta);
      if (component === undefined) {
        throw new Error(
          `no component defined in ${current.toStrings(current.value)}.meta`
        );
      }
      const props: ComponentProps<any, any, EventObject> = {
        ...params,
        ...current.context.params,
        current,
        send,
        service
      };
      return this.componentRenderer(component, props);
    };

    const serviceRenderer: Renderer<any, any, EventObject> = (
      current,
      send,
      service
    ) =>
      this.stateRenderer
        ? this.stateRenderer(
            componentRenderer(current, send, service),
            current,
            send,
            service
          )
        : componentRenderer(current, send, service);

    return <xstate-service service={this.service} renderer={serviceRenderer} />;
  }
}

// packages/stencil-xstate-router/src/components/xstate-router/index.tsx
import { EventObject, Condition, StateSchema, Interpreter } from 'xstate';
import { State as MachineState } from 'xstate';
import { Send } from 'stencil-xstate/dist/types';

export { Send, MachineState };

export type NavigationHandler = (url: string) => void;

export type RouteHandler<
  TContext,
  TSchema extends StateSchema,
  TEvent extends RouteEvent
> = (
  path: string,
  exact: boolean,
  send: Send<TContext, TSchema, TEvent>
) => VoidFunction;

export type StateRenderer<
  TContext,
  TSchema extends StateSchema,
  TEvent extends EventObject
> = (
  component: JSX.Element[] | JSX.Element,
  current: MachineState<TContext, TEvent>,
  send: Send<TContext, TSchema, TEvent>,
  service: Interpreter<TContext, TSchema, TEvent>
) => JSX.Element[] | JSX.Element;

export type ComponentRenderer<
  TContext,
  TSchema extends StateSchema,
  TEvent extends EventObject
> = (
  Component: string,
  props?: ComponentProps<TContext, TSchema, TEvent>
) => JSX.Element[] | JSX.Element;

export type RouteEvent = EventObject & {
  /**
   * URL routed to
   */
  url?: string;
  /**
   * Path routed to
   */
  path?: string;
  /**
   * Is this an exact match
   */
  exact?: boolean;
  /**
   * Route parameters
   */
  params?: Record<string, string>;
};

export type ComponentProps<
  TContext,
  TSchema extends StateSchema,
  TEvent extends EventObject
> = RouteMeta & {
  /**
   * Method to navigate to URL
   */
  navigate: (url: string) => void;
  /**
   * Current state
   */
  current: MachineState<TContext, TEvent>;
  /**
   * Sends events to the service
   */
  send: Send<TContext, TSchema, TEvent>;
  /**
   * Current service
   */
  service: Interpreter<TContext, TSchema, TEvent>;
};

export type RouteMeta = Record<string, any> & {
  /**
   * Component tag
   */
  component?: string;
};

export type RouteCondition<TContext, TEvent extends RouteEvent> = RouteEvent &
  Condition<TContext, TEvent>;

/**
 * Merges meta objects
 * @param source XState.State meta object
 * @param target Target object
 */
export const merge: <T extends RouteMeta>(source: T, target?: T | {}) => T = (
  source,
  target = {}
) =>
  Object.keys(source).reduce(
    (result, key) => Object.assign(result, source[key]),
    target
  );

/**
 * Renders a component
 * @param Component Component tag
 * @param props Component props
 */
export const renderComponent: ComponentRenderer<any, any, EventObject> = (
  Component,
  props
) => <Component {...props} />;
